# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e65b989ecd4b6125d817aad07586da558e5d633ba59a5da0fafffa99fa0f9228d62bc0077f1fbb0849360fa77e7d0ac9a20868ee708efc3a0bac3d8ca68e1f84

test:
  secret_key_base: 648bdacef1c3111835ddde697e145203588146bccbc3c3f22c4219eb7b95ac2a9d596802daef0123ea83c295a00ccffc97e4642af7c82a86a912bfe7190370e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
